### ISSUE TITLE
Add routes to model API to serve both models

### ISSUE THREAD

**Issue by kastentx** [IBM/MAX-Image-Segmenter#16]
If the `model/predict` route was changed to have both `/predict/mobile/` and `/predict/full` routes (or `model/mobile/predict/`) there would be no need to specify a single model at run/deploy time. Since both models are being downloaded anyways, there should be no increase in image size or performance overhead.

**Comment by bdwyer2** [comment]
Thanks for the idea however we want to change the image to only download one of the models. Take a look at #10
