### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by HeliumTang** [IBM/MAX-Image-Segmenter#45]
When I build the image, I got this error:

```
Step 10/12 : RUN if [ "$use_pre_trained_model" = "true" ] ; then       sha512sum -c sha512sums.txt ;
   else       if [ -d "./custom_assets/" ] ; then         rm -rf ./assets && ln -s ./custom_assets ./assets ;       fi     fi
 ---> Running in d1dd10f132bb
sha512sum: 'assets/frozen_inference_graph_mobile.pb'$'\r': No such file or directory
sha512sum: 'assets/frozen_inference_graph_full.pb'$'\r': No such file or directory
sha512sum: WARNING: 2 listed files could not be read
: FAILED open or readce_graph_mobile.pb
: FAILED open or readce_graph_full.pb
The command '/bin/sh -c if [ "$use_pre_trained_model" = "true" ] ; then       sha512sum -c sha512sums.txt ;     else       if [ -d "./custom_assets/" ] ; then         rm -rf ./assets && ln -s ./custom_assets ./assets ;       fi     fi' returned a non-zero code: 1
```

How to fix it? Thanks

**Comment by xuhdev** [comment]
Are you on Windows, and opened sha512sum.txt and saved it? You may have changed its [EOL](https://en.wikipedia.org/wiki/Newline) to dos format. [Redownload the file](https://raw.githubusercontent.com/IBM/MAX-Image-Segmenter/master/sha512sums.txt) should resolve this issue.

**Comment by HeliumTang** [comment]
> Are you on Windows, and opened sha512sum.txt and saved it? You may have changed its [EOL](https://en.wikipedia.org/wiki/Newline) to dos format. [Redownload the file](https://raw.githubusercontent.com/IBM/MAX-Image-Segmenter/master/sha512sums.txt) should resolve this issue.

Thanks. It fix the problem.
